### ISSUE TITLE
会员等级接口: 500错误(Source must not be null)

### ISSUE THREAD

**Issue by Disperito** [gaolingtech/issues#3]
![image](https://user-images.githubusercontent.com/50449082/99508984-2cfa6880-29c0-11eb-9055-90fb8e49db90.png)
![image](https://user-images.githubusercontent.com/50449082/99509009-34ba0d00-29c0-11eb-9214-5c13463b2633.png)
![image](https://user-images.githubusercontent.com/50449082/99508921-1ce28900-29c0-11eb-9e24-6b2a88d21b87.png)

**Comment by zhijunso** [comment]
接口变更为 /taobao/v1/level/list
http://maitiaogai.com:4999/web/#/5?page_id=59
